### ISSUE TITLE
incompatibility with woocommerce multi vendor store

### ISSUE THREAD

**Issue by IYassineBayoudhI** [Makewebbetter/mwb-bookings-for-woocommerce#58]
WordPress Version: 5.8
WooCommerce version: 5.5.2
yith frontend manager for woocommerce premium
Frontend manager -> Add product
page looks like this nothing works any link i press nothing happens 
![image](https://user-images.githubusercontent.com/67829078/127779169-4659a33f-7cc2-4f8a-bdcb-75fd05eba270.png)
it also changes the template 
this is mu original template : 
![image](https://user-images.githubusercontent.com/67829078/127779215-a1bf894d-5e55-4a1b-9f3a-312c8c2f4380.png)
I also get this error in the console
![image](https://user-images.githubusercontent.com/67829078/127779261-85c4bb6b-0006-42a5-8777-b3b6308a707d.png)

**Comment by makewebbetter-com** [comment]
Hello @IYassineBayoudhI ,

Thanks for showing your interest in our plugin.
The issue you are facing is due to incompatibility with "yith frontend manager for woocommerce premium". 

Currently "MWB Bookings for woocommerce" plugin isn't compatible with this plugin.
We suggest you run a test by deactivating the third-party plugins as well as by changing the themes.

Hope it may help you.

Regards,
